---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:buster-slim
    privileged: true
    pre_build_image: true
    required: true
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint .
